Is new statuses of homeworks
uncommunicativeness/homework-statuses-bot pull request #8
Opened 2022-09-07 22:36 UTC by kirillkormilcev

для отправки сообщения пользователя создал экземпляр бота прямо в методе, наверное можно по-другому, но не сообразил
при настроенных equals и hashcode в Homework сравнение листов работает норм, если выдачу из бд отсортировать
можно усовершенствовать, использовать Set, тогда сортировать выдачу домашек не надо будет, думаю
выдача уведомления пока кривая через toString(), надо будет допилить

2022-09-08 09:37 UTC, kirillkormilcev commented
Вывод поправил в более красивый, в целом можно выложить на хероку, чтобы тестить. На двух пользователях проверено.

2022-09-18 09:24 UTC, kirillkormilcev commented
Обновил пулл с учетом подсказки Алексея, работает на имеющемся экземпляре бота.

2022-09-18 10:14 UTC, SimpleTrooper requested changes

2022-09-18 10:14 UTC, SimpleTrooper commented on src/main/java/app/filatov/homeworkstatusesbot/model/Homework.java
> +    /*@Override
Думаю, что лучше без таких комментариев в коде, чтобы улучшить читаемость и не засорять лишний раз

2022-09-18 10:14 UTC, SimpleTrooper commented on src/main/java/app/filatov/homeworkstatusesbot/model/repository/HomeworkRepository.java
> +    @Query("""
Здесь можно сократить - вместо прямого SQL запроса назвать метод, например findAllByUserIdOrderByDateUpdatedDesc и фреймворк сам сгенерирует запрос

2022-09-18 10:14 UTC, SimpleTrooper commented on src/main/java/app/filatov/homeworkstatusesbot/service/update/NewChangesServiceSimpleImpl.java
> +            for (Homework homework : newHomeworks) {
Консольный вывод, наверное, не нужен здесь. Можно просто в лог писать, например, что были получены изменения в домашних работах

2022-09-18 10:14 UTC, SimpleTrooper commented on src/main/java/app/filatov/homeworkstatusesbot/service/update/NewChangesServiceSimpleImpl.java
> +            log.warn("Пользователь {} не найден.", userId);
Тут лучше выйти из метода, если пользователя не нашли. Либо исключение выкинуть

2022-09-18 10:14 UTC, SimpleTrooper commented on src/main/resources/application.yml
> +      ddl-auto: create
Здесь создаем каждый раз новую базу при перезапуске. Лучше оставить update

2022-09-18 11:34 UTC, kirillkormilcev commented
Поправил

2022-09-20 11:58 UTC, uncommunicativeness reviewed
Кажется все отлично, у меня нет предложений по улучшению

2022-09-20 12:31 UTC, merged